apiVersion: v1
kind: Service
metadata:
  name: model-server
  labels:
    app: model-server
spec:
  type: NodePort
  ports:
    - protocol: "TCP"
      port: 5001
      targetPort: 5001
  selector:
    app: model-server